import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./Styles/page.module.css";
import "./Styles/globals.css";
import './Styles/reset.scss'
import './Styles/variables.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
